/*
* Archipelago for Half-Life (Sven Co-op) -- shared state and campaign data.
*
* checkdata.txt is generated by tools/gen_checkdata.py from the same JSON the
* apworld reads, so location ids here always match the ones the server knows.
*/

const string AP_DIR = "scripts/plugins/store/archipelago/";
const string AP_CHECKDATA = AP_DIR + "checkdata.txt";
const string AP_IN = AP_DIR + "ap_in.txt";
const string AP_OUT = AP_DIR + "ap_out.txt";

// "go back to the hub once the next map has loaded". A file rather than a global
// because the whole point is to survive the map change that is about to happen.
const string AP_PENDING = AP_DIR + "ap_pending.txt";

// How much DeathLink amnesty is left. Also a file, and for the same reason: the
// allowance is spent across a whole run, not a single map.
const string AP_AMNESTY = AP_DIR + "ap_amnesty.txt";

const string HUB_MAP = "-sp_campaign_portal";

// Location trigger kinds, as emitted by gen_checkdata.py.
const string TRIGGER_PICKUP = "pickup";
const string TRIGGER_KILL = "kill";
const string TRIGGER_KILL_COUNT = "kill_count";
const string TRIGGER_MAP_REACHED = "map_reached";
const string TRIGGER_CHAPTER_COMPLETE = "chapter_complete";
const string TRIGGER_CHARGER = "charger";
const string TRIGGER_WEAPON_PICKUP = "weapon_pickup";

class APChapter
{
	int index;
	string key;
	string name;
	array<string> maps;
	bool isGoal;

	string FirstMap() const { return maps[0]; }
	string LastMap() const { return maps[maps.length() - 1]; }

	bool HasMap( const string& in szMap ) const
	{
		for( uint i = 0; i < maps.length(); ++i )
			if( maps[i] == szMap )
				return true;
		return false;
	}
}

class APLocation
{
	int id;
	string map;
	string kind;
	string arg;          // classnames / classname / count / chapter key
	array<string> args;  // arg split on ',' for pickup lists
	string name;
}

/*
* Everything the client has told us. Rebuilt from ap_in.txt on every read, so a
* map change or a plugin reload costs nothing -- the client is the source of
* truth and we are a pure view of it.
*/
class APState
{
	dictionary unlockedChapters;  // chapter key -> true
	// Missions the seed left out. Not the same as locked: no item will ever
	// unlock these, so the list says so instead of implying a key exists.
	dictionary excludedChapters;
	dictionary unlockedItems;     // AP item name -> true
	bool goalOpen = false;
	bool connected = false;
	bool deathLink = false;
	// Deaths the lobby may take before one is reported to the multiworld.
	// 0 means every death counts, which is what an older client implies too.
	int deathLinkAmnesty = 0;
	int lastEventSeq = 0;

	bool ChapterUnlocked( const string& in szKey ) const
	{
		return unlockedChapters.exists( szKey );
	}

	bool ChapterExcluded( const string& in szKey ) const
	{
		return excludedChapters.exists( szKey );
	}

	bool ItemUnlocked( const string& in szItem ) const
	{
		return unlockedItems.exists( szItem );
	}
}

// --- globals --------------------------------------------------------------

array<APChapter@> g_Chapters;
array<APLocation@> g_Locations;

// Fingerprint of the id map checkdata.txt was generated from. If the client
// reports a different one, our location ids mean different things than the
// seed's do and every check we send would land on the wrong location.
string g_szDataVersion;
bool g_bDataMismatch = false;

// classname -> AP item name; a pickup of this classname is refused until owned.
dictionary g_LockedClassnames;
// classnames always granted regardless of the multiworld.
array<string> g_StartingWeapons;

// Locations relevant to the map we are currently on, bucketed by trigger kind
// so the hot paths (pickup / kill) never walk all 174 entries.
array<APLocation@> g_MapPickups;
array<APLocation@> g_MapKills;
array<APLocation@> g_MapKillCounts;
array<APLocation@> g_MapChargers;

// "First time you find this weapon", at the one map Half-Life would have given
// it to you. Map-filtered like every other check: picking the same weapon up
// somewhere later in the campaign is not the moment this check is about.
array<APLocation@> g_WeaponPickups;

APState g_State;

// Checks already sent this session, so a re-entered map does not spam the client.
dictionary g_SentChecks;

string g_szCurrentMap;
APChapter@ g_CurrentChapter = null;
int g_iMapKills = 0;

/*
* Are we actually *playing* the mission this map belongs to?
*
* False when the campaign chained us into a mission we never unlocked, and false
* while we are bouncing back to the hub. Both cases look identical to a genuine
* mission from inside MapChange -- the engine is leaving the last map of a
* chapter either way -- and treating them alike is what credited Office Complex
* the moment Unforeseen Consequences ended.
*/
bool g_bMissionActive = false;

// Set just before we issue our own changelevel. A transition we asked for is
// never a mission completion: `!hub` out of a one-map mission is walking away
// from it, not finishing it.
bool g_bSelfChange = false;

// Tri-state, because the suit is announced on the transition and a map load must
// not re-announce it: -1 unknown, 0 not owned, 1 owned.
int g_iSuitOwned = -1;

// Set to g_Engine.time + a short window while a lobby wipe is in progress, so
// the deaths we cause are neither reported nor able to re-trigger the wipe.
float g_flDeathLinkImmuneUntil = 0.0f;

// Deaths still forgiven before the next one goes out to the multiworld. -1 means
// "not loaded yet"; it is filled from the amnesty setting the first time a death
// has to be judged, since the snapshot may not have arrived at map load.
int g_iAmnestyRemaining = -1;

// --- helpers --------------------------------------------------------------

void APLog( const string& in szMessage )
{
	g_Game.AlertMessage( at_console, "[AP] " + szMessage + "\n" );
}

/*
* ReadLine leaves the line ending on when the file was written by a Windows
* tool, and our Python side writes plain "\n" -- strip both so string compares
* against classnames and chapter keys behave.
*/
string APTrim( const string& in szValue )
{
	uint uiStart = 0;
	uint uiEnd = szValue.Length();

	while( uiStart < uiEnd )
	{
		string szChar = szValue.SubString( uiStart, 1 );
		if( szChar != " " && szChar != "\t" && szChar != "\r" && szChar != "\n" )
			break;
		++uiStart;
	}

	while( uiEnd > uiStart )
	{
		string szChar = szValue.SubString( uiEnd - 1, 1 );
		if( szChar != " " && szChar != "\t" && szChar != "\r" && szChar != "\n" )
			break;
		--uiEnd;
	}

	return szValue.SubString( uiStart, uiEnd - uiStart );
}

/*
* Strip the bridge's field separators out of free text.
*
* Player names and chat messages are the only values in the protocol that a
* person controls, so they are the only ones that can desync the parser.
*/
string APSanitise( const string& in szValue )
{
	string szOut;

	for( uint i = 0; i < szValue.Length(); ++i )
	{
		string szChar = szValue.SubString( i, 1 );
		if( szChar == "|" )
			szChar = "/";
		else if( szChar == "\n" || szChar == "\r" )
			szChar = " ";
		szOut += szChar;
	}

	return szOut;
}

/*
* Did checkdata.txt load? Anything that strips or gates has to check this first:
* empty tables mean "we do not know", not "nothing is allowed".
*/
bool CheckDataLoaded()
{
	return g_Chapters.length() > 0 && g_StartingWeapons.length() > 0;
}

APChapter@ ChapterByKey( const string& in szKey )
{
	for( uint i = 0; i < g_Chapters.length(); ++i )
		if( g_Chapters[i].key == szKey )
			return g_Chapters[i];
	return null;
}

APChapter@ ChapterForMap( const string& in szMap )
{
	for( uint i = 0; i < g_Chapters.length(); ++i )
		if( g_Chapters[i].HasMap( szMap ) )
			return g_Chapters[i];
	return null;
}

bool ChapterPlayable( APChapter@ pChapter )
{
	if( pChapter is null )
		return false;
	if( pChapter.isGoal )
		return g_State.goalOpen;
	return g_State.ChapterUnlocked( pChapter.key );
}

/*
* Load checkdata.txt. Called once per map load; the file is small (~180 lines)
* and re-reading it keeps the plugin stateless across map changes.
*/
void LoadCheckData()
{
	g_Chapters.resize( 0 );
	g_Locations.resize( 0 );
	g_LockedClassnames.deleteAll();
	g_StartingWeapons.resize( 0 );

	File@ pFile = g_FileSystem.OpenFile( AP_CHECKDATA, OpenFile::READ );

	if( pFile is null || !pFile.IsOpen() )
	{
		APLog( "FATAL: could not open " + AP_CHECKDATA );
		return;
	}

	while( !pFile.EOFReached() )
	{
		string szRaw;
		pFile.ReadLine( szRaw );
		string szLine = APTrim( szRaw );
		if( szLine.Length() == 0 || szLine.SubString( 0, 1 ) == "#" )
			continue;

		array<string>@ parts = szLine.Split( "|" );
		if( parts.length() < 2 )
			continue;

		if( parts[0] == "C" && parts.length() >= 6 )
		{
			APChapter chapter;
			chapter.index = atoi( parts[1] );
			chapter.key = parts[2];
			chapter.name = parts[3];
			chapter.maps = parts[4].Split( "," );
			chapter.isGoal = parts[5] == "1";
			g_Chapters.insertLast( @chapter );
		}
		else if( parts[0] == "L" && parts.length() >= 6 )
		{
			APLocation location;
			location.id = atoi( parts[1] );
			location.map = parts[2];
			location.kind = parts[3];
			location.arg = parts[4];
			location.args = parts[4].Split( "," );
			location.name = parts[5];
			g_Locations.insertLast( @location );
		}
		else if( parts[0] == "K" && parts.length() >= 3 )
		{
			g_LockedClassnames[ parts[1] ] = parts[2];
		}
		else if( parts[0] == "S" )
		{
			g_StartingWeapons.insertLast( parts[1] );
		}
		else if( parts[0] == "D" )
		{
			g_szDataVersion = parts[1];
		}
	}

	pFile.Close();
	APLog( "loaded " + g_Chapters.length() + " chapters, " + g_Locations.length() + " locations" );
}

/*
* Narrow the location list down to the current map so the pickup and kill hooks
* stay cheap.
*/
void IndexCurrentMap()
{
	g_MapPickups.resize( 0 );
	g_MapKills.resize( 0 );
	g_MapKillCounts.resize( 0 );
	g_MapChargers.resize( 0 );
	g_WeaponPickups.resize( 0 );
	g_iMapKills = 0;

	for( uint i = 0; i < g_Locations.length(); ++i )
	{
		APLocation@ pLocation = g_Locations[i];
		if( pLocation.map != g_szCurrentMap )
			continue;

		if( pLocation.kind == TRIGGER_WEAPON_PICKUP )
			g_WeaponPickups.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_PICKUP )
			g_MapPickups.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_KILL )
			g_MapKills.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_KILL_COUNT )
			g_MapKillCounts.insertLast( pLocation );
		else if( pLocation.kind == TRIGGER_CHARGER )
			g_MapChargers.insertLast( pLocation );
	}
}
