// `checkdata.txt`: what the seed's locations are, generated by
// `tools/gen_checkdata.py` from the same `campaign.json` the apworld reads.
//
// Read once per map load. The format is line-oriented and pipe-delimited; see
// the header of the generated file for the record types.
//
// A charger's identity is its rounded world-space centre, never its brush model
// index: Valve recompiles single-player maps from time to time and a recompile
// renumbers brush models, which would silently repoint every charger id in that
// map. `RoundPosition` here has to agree exactly with `charger_key_position` in
// `tools/build_campaign_data.py`.

#pragma once

#include <string>
#include <vector>

namespace ap {

enum class TriggerType { MapReached, ChapterComplete, Charger, WeaponPickup };

struct Location {
    long id = 0;
    std::string map;
    TriggerType type = TriggerType::MapReached;
    std::string arg;    // charger: "<classname>@<x y z>"; weapon: "cls,cls"
    std::string name;
    bool has_position = false;
    float position[3] = {0, 0, 0};   // for ap_find
};

struct Chapter {
    int index = 0;
    std::string key;
    std::string name;
    std::vector<std::string> maps;
    bool is_goal = false;
};

struct CheckData {
    int format_version = 0;
    std::string data_version;   // must match the client's, or ids differ
    std::string goal_chapter;
    std::vector<Chapter> chapters;
    std::vector<Location> locations;

    // classname -> the item name that must arrive before it may be picked up.
    std::vector<std::pair<std::string, std::string>> gated_classnames;
    // Granted from the first spawn and never taken away.
    std::vector<std::string> starting_weapons;

    // Which mission a map belongs to, or "" for a map not in the campaign.
    const Chapter* ChapterOfMap(const std::string& map) const;
};

bool LoadCheckData(const std::string& path, CheckData& out);

// The grid a charger's position is snapped to before it becomes its identity.
// Four units: well inside the body of a charger, so two real units can never
// round together, but coarse enough to absorb the difference between the float
// the compiler wrote and the one the running game computes.
constexpr float kChargerPositionGrid = 4.0f;

void RoundPosition(const float in[3], float out[3]);

}  // namespace ap
