"""Checks that older seeds still contain but new seeds never get.

Kept so a seed generated by an earlier release plays to the end on the current
game and client. Their ids stay reserved in `ids.json`; the apworld never
creates them, and nothing here is read during generation.
"""

# Removed locations, `{id: (name as the old seeds call it, map it was on)}`.
# Nothing in the game fires them any more, and a seed that put progression on
# one would otherwise never finish, so the client sends one for the player once
# they have reached its map (that map's "Reached" check is checked).
LEGACY_LOCATIONS: dict[int, tuple[str, str]] = {
    # Sealed in a pocket only reachable through a transition; in v0.2 to v0.3.
    7760052: ("We've Got Hostiles - Health Charger 1 (Part 2)", "c1a3d"),
    # A healing pool there is no way into; in v0.3-pre on.
    7760282: ("We Are Not Alone - Healing Pool (Part 2)", "of3a1b"),
    # Out of reach in play; in v0.3-pre.
    7760297: ("Vicarious Reality: Health Charger 3 (Part 2)", "of4a2"),
}
