"""Emit the game's data file from `campaign.json`.

The server dll reads a line-oriented, pipe-delimited format rather than JSON:
GoldSrc ships no JSON parser and this needs none, since every record is one
`strtok` pass. Regenerating it from the same JSON the apworld reads is what keeps
location ids from drifting between the two halves of the project.

Usage:
    python tools/gen_checkdata.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from campaign_layout import CLASSNAME_TO_ITEM, STARTING_WEAPONS

REPO_ROOT = Path(__file__).resolve().parent.parent
CAMPAIGN_PATH = REPO_ROOT / "apworld" / "half_life" / "data" / "campaign.json"
# Bundled inside the world package so a zipped .apworld can install the mod
# folder itself. It lands in `<Half-Life>/hlap/archipelago/`, next to the bridge
# files, which is the one directory both halves read and write.
OUT_PATH = (
    REPO_ROOT / "apworld" / "half_life" / "mod" / "files"
    / "archipelago" / "checkdata.txt"
)

# 1 is this project's first format. It is not the Sven Co-op world's format 3
# with records removed: chapters carry no campaign, chargers are keyed by
# position rather than brush model, and there was never a released seed to keep
# reading. A future hub map adds a `P|<button targetname>|<chapter key>` record
# and nothing else changes.
FORMAT_VERSION = 1


def render(campaign: dict) -> str:
    lines: list[str] = [
        "# Generated by tools/gen_checkdata.py -- do not edit by hand.",
        "# Record types:",
        "#   V|<format version>",
        "#   G|<goal chapter key>",
        "#   C|<index>|<key>|<name>|<map,map,...>|<is_goal>",
        "#   L|<id>|<map>|<type>|<arg>|<name>[|<x y z>]",
        "#   K|<classname>|<item name>      weapon pickup that must be unlocked",
        "#   S|<classname>                  always granted, never randomised",
        "#   D|<data version>               must match the client's, or ids differ",
        "# A charger's <arg> is <classname>@<x y z>, the rounded world-space centre",
        "# of the unit. Brush model indices are deliberately not used: the game's",
        "# maps are recompiled by Valve from time to time and that renumbers them.",
        f"V|{FORMAT_VERSION}",
        f"D|{campaign['data_version']}",
        f"G|{campaign['goal_chapter']}",
    ]

    for chapter in campaign["chapters"]:
        lines.append(
            "C|{index}|{key}|{name}|{maps}|{goal}".format(
                index=chapter["index"],
                key=chapter["key"],
                name=chapter["name"],
                maps=",".join(chapter["maps"]),
                goal=1 if chapter["is_goal"] else 0,
            )
        )

    for location in campaign["locations"]:
        trigger = location["trigger"]
        kind = trigger["type"]
        if kind in ("pickup", "weapon_pickup"):
            arg = ",".join(trigger["classnames"])
        elif kind == "kill":
            arg = trigger["classname"]
        elif kind == "kill_count":
            arg = str(trigger["count"])
        elif kind == "chapter_complete":
            arg = trigger["chapter"]
        elif kind == "charger":
            # What the game matches the entity a player pressed +use on against:
            # its classname and where it stands, rounded the same way on both
            # sides. See `charger_key_position` in build_campaign_data.py.
            arg = f"{trigger['classname']}@{trigger['at']}"
        else:  # map_reached
            arg = ""
        # A seventh field where we know where the thing is, which is what
        # `ap_find` points at.
        position = location.get("position")
        record = "L|{id}|{map}|{kind}|{arg}|{name}".format(
            id=location["id"],
            map=location["map"],
            kind=kind,
            arg=arg,
            name=location["name"],
        )
        if position:
            record += "|" + " ".join(str(value) for value in position)
        lines.append(record)

    # Every classname the game must refuse until the matching item arrives.
    for classname, item in sorted(CLASSNAME_TO_ITEM.items()):
        lines.append(f"K|{classname}|{item}")

    for classname in STARTING_WEAPONS:
        lines.append(f"S|{classname}")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--campaign", type=Path, default=CAMPAIGN_PATH)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    args = parser.parse_args(argv)

    campaign = json.loads(args.campaign.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(campaign), encoding="utf-8")

    lockable = len(CLASSNAME_TO_ITEM)
    print(f"wrote {args.out}")
    print(f"  chapters {len(campaign['chapters'])}, locations {len(campaign['locations'])},"
          f" lockable classnames {lockable}")
    unused = set(CLASSNAME_TO_ITEM) - {
        c for l in campaign["locations"]
        if l["trigger"]["type"] in ("pickup", "weapon_pickup")
        for c in l["trigger"]["classnames"]
    }
    if unused:
        print(f"  note: no pickup location exists for {sorted(unused)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
