"""Emit the AngelScript plugin's data file from `campaign.json`.

AngelScript has no JSON parser, so the plugin reads a line-oriented, pipe
delimited format that `string.Split("|")` handles in one call. Regenerating this
from the same JSON the apworld reads is what keeps location ids from drifting
between the two halves of the project.

Usage:
    python tools/gen_checkdata.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from campaign_layout import CLASSNAME_TO_ITEM, STARTING_WEAPONS

REPO_ROOT = Path(__file__).resolve().parent.parent
CAMPAIGN_PATH = REPO_ROOT / "apworld" / "half_life_sven" / "data" / "campaign.json"
# The plugin tree is bundled inside the world package so a zipped .apworld can
# install itself. Plugins may only read and write under scripts/plugins/store/,
# so the data file sits there rather than next to the .as sources.
OUT_PATH = (
    REPO_ROOT / "apworld" / "half_life_sven" / "plugin"
    / "plugins" / "store" / "archipelago" / "checkdata.txt"
)

# 2 added the campaign records, the console table, and a seventh field on `C`.
# All three are additive: a plugin reading the older format ignores what it does
# not recognise and behaves exactly as it did.
FORMAT_VERSION = 2


def render(campaign: dict) -> str:
    lines: list[str] = [
        "# Generated by tools/gen_checkdata.py -- do not edit by hand.",
        "# Record types:",
        "#   V|<format version>",
        "#   M|<key>|<name>|<goal chapter>  a campaign",
        "#   C|<index>|<key>|<name>|<map,map,...>|<is_goal>|<campaign key>",
        "#   P|<console>|<chapter key>      hub console button -> the mission it enters",
        "#   L|<id>|<map>|<type>|<arg>|<name>",
        "#   K|<classname>|<item name>      weapon pickup that must be unlocked",
        "#   S|<classname>                  always granted, never randomised",
        "#   D|<data version>               must match the client's, or ids differ",
        f"V|{FORMAT_VERSION}",
        f"D|{campaign['data_version']}",
    ]

    for entry in campaign.get("campaigns", ()):
        lines.append(
            "M|{key}|{name}|{goal}".format(
                key=entry["key"], name=entry["name"], goal=entry["goal_chapter"],
            )
        )

    for chapter in campaign["chapters"]:
        lines.append(
            "C|{index}|{key}|{name}|{maps}|{goal}|{campaign}".format(
                index=chapter["index"],
                key=chapter["key"],
                name=chapter["name"],
                maps=",".join(chapter["maps"]),
                goal=1 if chapter["is_goal"] else 0,
                campaign=chapter.get("campaign", ""),
            )
        )

    # The hub numbers its consoles differently in every campaign -- Half-Life's
    # are unpadded and start at 1, Opposing Force's are padded and skip 06 -- so
    # the plugin is handed the mapping rather than deriving it from a targetname.
    for entry in campaign.get("campaigns", ()):
        for console, chapter_key in sorted(entry.get("consoles", {}).items()):
            lines.append(f"P|{console}|{chapter_key}")

    for location in campaign["locations"]:
        trigger = location["trigger"]
        kind = trigger["type"]
        if kind in ("pickup", "weapon_pickup"):
            arg = ",".join(trigger["classnames"])
        elif kind == "kill":
            arg = trigger["classname"]
        elif kind == "kill_count":
            arg = str(trigger["count"])
        elif kind == "chapter_complete":
            arg = trigger["chapter"]
        elif kind == "charger":
            # `<classname>:<brush model>`, which is what the plugin matches the
            # entity a player pressed +use on against.
            arg = f"{trigger['classname']}:{trigger['model']}"
        else:  # map_reached
            arg = ""
        lines.append(
            "L|{id}|{map}|{kind}|{arg}|{name}".format(
                id=location["id"],
                map=location["map"],
                kind=kind,
                arg=arg,
                name=location["name"],
            )
        )

    # Every classname the plugin must refuse until the matching item arrives.
    for classname, item in sorted(CLASSNAME_TO_ITEM.items()):
        lines.append(f"K|{classname}|{item}")

    for classname in STARTING_WEAPONS:
        lines.append(f"S|{classname}")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--campaign", type=Path, default=CAMPAIGN_PATH)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    args = parser.parse_args(argv)

    campaign = json.loads(args.campaign.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(campaign), encoding="utf-8")

    lockable = len(CLASSNAME_TO_ITEM)
    print(f"wrote {args.out}")
    print(f"  chapters {len(campaign['chapters'])}, locations {len(campaign['locations'])},"
          f" lockable classnames {lockable}")
    unused = set(CLASSNAME_TO_ITEM) - {
        c for l in campaign["locations"]
        if l["trigger"]["type"] in ("pickup", "weapon_pickup")
        for c in l["trigger"]["classnames"]
    }
    if unused:
        print(f"  note: no pickup location exists for {sorted(unused)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
